version: "3.9"
services:
  db:
    image: 'mysql'
    container_name: mysqlDBPrecato
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: database_name
    ports:
      - '3307:3306'
    expose:
      - 3307
    volumes:
      - ./data/db:/var/lib/mysql
    restart: on-failure


  server:
      container_name: DESAFIO-PRECATO
      build: '.'
      volumes:
        - ./:/desafioprecato
        - ./node_modules:/desafioprecato/node_modules
      command: ["/wait-for-it.sh", "db:3306", "--", "node", "server.js"]
      environment:
        NODE_ENV: development
      depends_on:
        - db
      ports:
        - '3000:3000'
      restart: on-failure
