swagger: '2.0'
info:
  title: Desafio Precato
  version: 1.0.0
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      description: Retorna todos os usuários
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      description: Cria um novo usuário
      parameters:
        - in: body
          name: body
          description: Objeto User para ser criado
          required: true
          schema:
            $ref: '#/definitions/UserInput'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/User'
  /users/{id}:
    parameters:
      - in: path
        name: id
        type: string
        required: true
        description: Id do usuário a ser buscado
    put:
      description: Atualiza um usuário
      parameters:
        - in: body
          name: body
          description: Objeto User para ser atualizado
          required: true
          schema:
            $ref: '#/definitions/UserInput'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/User'
        '404':
          description: Not Found
    delete:
      description: Deleta um usuário
      responses:
        '200':
          description: Ok
        '404':
          description: Not Found
  /users/{start_date}/{end_date}:
    parameters:
      - in: path
        name: start_date
        type: string
        required: true
        description: Data inicial para busca, formato - YYYY-MM-DD
      - in: path
        name: end_date
        type: string
        required: true
        description: Data final para busca, formato - YYYY-MM-DD
    get:
      description: Retorna usuários criados entre as datas informadas
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              error:
                type: string
              example:
                error: 'dates required!'
definitions:
  User:
    type: object
    properties:
      _id:
        type: string
      name:
        type: string
      email:
        type: string
      cpf:
        type: string
      phone:
        type: string
      created_at:
        type: string
  UserInput:
    type: object
    properties:
      name:
        type: string
        required: true
      email:
        type: string
        required: true
      cpf:
        type: string
        required: true
      phone:
        type: string
        required: true
